// Code generated by "esc -o bindata/esc.go -pkg=bindata templates"; DO NOT EDIT.

package bindata

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"io"
	"io/ioutil"
	"net/http"
	"os"
	"path"
	"sync"
	"time"
)

type _escLocalFS struct{}

var _escLocal _escLocalFS

type _escStaticFS struct{}

var _escStatic _escStaticFS

type _escDirectory struct {
	fs   http.FileSystem
	name string
}

type _escFile struct {
	compressed string
	size       int64
	modtime    int64
	local      string
	isDir      bool

	once sync.Once
	data []byte
	name string
}

func (_escLocalFS) Open(name string) (http.File, error) {
	f, present := _escData[path.Clean(name)]
	if !present {
		return nil, os.ErrNotExist
	}
	return os.Open(f.local)
}

func (_escStaticFS) prepare(name string) (*_escFile, error) {
	f, present := _escData[path.Clean(name)]
	if !present {
		return nil, os.ErrNotExist
	}
	var err error
	f.once.Do(func() {
		f.name = path.Base(name)
		if f.size == 0 {
			return
		}
		var gr *gzip.Reader
		b64 := base64.NewDecoder(base64.StdEncoding, bytes.NewBufferString(f.compressed))
		gr, err = gzip.NewReader(b64)
		if err != nil {
			return
		}
		f.data, err = ioutil.ReadAll(gr)
	})
	if err != nil {
		return nil, err
	}
	return f, nil
}

func (fs _escStaticFS) Open(name string) (http.File, error) {
	f, err := fs.prepare(name)
	if err != nil {
		return nil, err
	}
	return f.File()
}

func (dir _escDirectory) Open(name string) (http.File, error) {
	return dir.fs.Open(dir.name + name)
}

func (f *_escFile) File() (http.File, error) {
	type httpFile struct {
		*bytes.Reader
		*_escFile
	}
	return &httpFile{
		Reader:   bytes.NewReader(f.data),
		_escFile: f,
	}, nil
}

func (f *_escFile) Close() error {
	return nil
}

func (f *_escFile) Readdir(count int) ([]os.FileInfo, error) {
	if !f.isDir {
		return nil, fmt.Errorf(" escFile.Readdir: '%s' is not directory", f.name)
	}

	fis, ok := _escDirs[f.local]
	if !ok {
		return nil, fmt.Errorf(" escFile.Readdir: '%s' is directory, but we have no info about content of this dir, local=%s", f.name, f.local)
	}
	limit := count
	if count <= 0 || limit > len(fis) {
		limit = len(fis)
	}

	if len(fis) == 0 && count > 0 {
		return nil, io.EOF
	}

	return fis[0:limit], nil
}

func (f *_escFile) Stat() (os.FileInfo, error) {
	return f, nil
}

func (f *_escFile) Name() string {
	return f.name
}

func (f *_escFile) Size() int64 {
	return f.size
}

func (f *_escFile) Mode() os.FileMode {
	return 0
}

func (f *_escFile) ModTime() time.Time {
	return time.Unix(f.modtime, 0)
}

func (f *_escFile) IsDir() bool {
	return f.isDir
}

func (f *_escFile) Sys() interface{} {
	return f
}

// FS returns a http.Filesystem for the embedded assets. If useLocal is true,
// the filesystem's contents are instead used.
func FS(useLocal bool) http.FileSystem {
	if useLocal {
		return _escLocal
	}
	return _escStatic
}

// Dir returns a http.Filesystem for the embedded assets on a given prefix dir.
// If useLocal is true, the filesystem's contents are instead used.
func Dir(useLocal bool, name string) http.FileSystem {
	if useLocal {
		return _escDirectory{fs: _escLocal, name: name}
	}
	return _escDirectory{fs: _escStatic, name: name}
}

// FSByte returns the named file from the embedded assets. If useLocal is
// true, the filesystem's contents are instead used.
func FSByte(useLocal bool, name string) ([]byte, error) {
	if useLocal {
		f, err := _escLocal.Open(name)
		if err != nil {
			return nil, err
		}
		b, err := ioutil.ReadAll(f)
		_ = f.Close()
		return b, err
	}
	f, err := _escStatic.prepare(name)
	if err != nil {
		return nil, err
	}
	return f.data, nil
}

// FSMustByte is the same as FSByte, but panics if name is not present.
func FSMustByte(useLocal bool, name string) []byte {
	b, err := FSByte(useLocal, name)
	if err != nil {
		panic(err)
	}
	return b
}

// FSString is the string version of FSByte.
func FSString(useLocal bool, name string) (string, error) {
	b, err := FSByte(useLocal, name)
	return string(b), err
}

// FSMustString is the string version of FSMustByte.
func FSMustString(useLocal bool, name string) string {
	return string(FSMustByte(useLocal, name))
}

var _escData = map[string]*_escFile{

	"/templates/call.tmpl": {
		name:    "call.tmpl",
		local:   "templates/call.tmpl",
		size:    241,
		modtime: 1617338274,
		compressed: `
H4sIAAAAAAAC/0SOQWrDQAxFryKMFy0YHaDQA3hTSlvatRjLrsCeFo2SEITuHsY4mdWHP2/el/vEs2SG
LtG6dhHuF7FfwA9OLGfW2sgM+c8Ax/JpekoWYYbunKf6eicBI1qLb7RxxJO7Ul4Yehmg5xVeXgHfSWlj
Yy2HvZeIAR5/296PitUbzJB0KU2/K+riTuPX9Z9xLN+kQpOkCMTG7vF85C0AAP//ZQi8iPEAAAA=
`,
	},

	"/templates/function.tmpl": {
		name:    "function.tmpl",
		local:   "templates/function.tmpl",
		size:    4751,
		modtime: 1638518304,
		compressed: `
H4sIAAAAAAAC/7RYXYvbOhO+tn/FNKTFXlyH3mbJRT+2Lwtvd8t2aQ+UQ3HjcWrWkX1kZZcg9N8PI8m2
FDvZDzg3iS2NNM/MPPORSJljUTKEWbFja1HWbKZUKOVbmBewXEGqVBjSFkiZ3mIrrrItKhUJOBPYipJt
0tsYZBjQkYdS/IH0BtdY3iNXKgz0cllAetl+E3y3FnqxX/1cYpW3Zi0Q+wah0CvQamG610rzjG3w4AAA
wHD/JRPIi2yNdjfQu/oAWQFn23p990vKtBdsL1lRp1/vNsam9Eu9vhvvm01zJWnDqnVUuBrIQ/vGF2a5
ffXfei90S87zwSNZR47/mvFsiwK5Nl87K+Mbz1WOo8YntEK9NALraPT1U4hbooGUGgf5IldqmzU/W8FL
tvnbaJfSeOXn8E4XWFB0NGK1sOdjpVi2RTA3WFGLYoJBnRMylg80OmCCZY350isNxybjCETdyG6fme/E
+O2MPuNwHFUpO/3jqB4J2YlABYHWRh8TZ5xo3WC7q0Tb6fmRMXEqUL3KGxQ7ztoLzmvrsIeMiQvO4Xdd
VwfRpYAsFnB7/el6Ce/zHCjCsM5abFMSDYOAYrOEGa29myX6vB8VeKvVmOybmzhQpXAjcipm9nwXtaUN
mxyyxnhl/pxkP5mZSymjHItsV4nvWQXan7FSyWLxrJxNHiXLUxW9lEZL+hgVxclc95L9OC7ffs9glbyM
sE9QljyXy8siq1ocHzvBTL/vdKQbdg7IaAvG8tGKYZvSpqZ+kl6ya54jj6z7ntGmes2BTaTlqiess967
/KAtfUHxp87p8f9la8xbLAzclG5TKr346+vFx9soTqW0XSySct5UyJarqEIGqWZIG+sq06dd2SQwv290
9zcC+nYvqh/2dCGJxUpJWRawEaCvhijLc7oE3lHQu/Juw0Y3xTbMBIY7YMzqIRiezO+5xmL2T2DhLhbu
YOEeFgh7DsXpe7a/LbfYRnECsFg02t6l4/bBA5TC+lMfPQfgGpArPED0hZ14Ou9etnUssU7qliB2ao89
3+374v6bSkLdzIuag/ZJVHNIv+1+m5Zu2vFle5XdYR4bnzsNnnpA19N/WcwJCGFGAeNFY7K5jlJCiOVK
iDAI1oJXJGgz5AofPtZM8LqqkEeC7MmxQA4kl34uWdn+ieKwd8DECDCV0NPp7NSxl02MQqR9Eg2T3Qoe
HR6v8OHU/BiRtbH1ncuCsiCd3bjyagWsrGyJAWcnetMjS4Ce++klUA41OmIMFfKwxHYU8BaJ5FWFlVIm
xkKcj07qXt4JekyhE/R9LqVmoD4l0psdpfgRVgmR2lfDLV11Rz8qJhH2z1Hsg3Tsn54kj/waGY18muW6
D+8b1MIZV+pNHz2z/j2rdqjUaG7xKUc7lgPLaXYlU6NHMNGQRy9uifLn/M7MH7wUvfX+SLCCN7/3Atv0
w64okMunKLQ0MNXjmlV7t2HH4/VrhtpLMfTIBG6bKhMIM27mhxnMC11/hp11VlVm+RiKiUmBMslE7RCY
UoCcm6hOKTnva1pEciYHY/oWIu2GaRtmkeori2jm3rXFts02aE1BkoAVvL5PoDv++n6WeOpL1ux645Hz
xFEWD4zopkFv2NJ7bjKDUqYZdem1rpko2Q6P95vgJKXGKo9xSnv9f7UYEqfnWPpN/8KL4nNHxHjV/X0T
uvO71fEha8u1O5h3wZ0XU/yipPQwuH6uSoaHgX4ynv9I/yuORYVrkX5CbC7+2WVV1N+Q+IBiF1Efvafw
sANswX7ZVaJsKg+sxTNw9RGiHgV5/F+NA54CGeSOKipUYdjx9N8AAAD//6iaYRmPEgAA
`,
	},

	"/templates/header.tmpl": {
		name:    "header.tmpl",
		local:   "templates/header.tmpl",
		size:    143,
		modtime: 1617715414,
		compressed: `
H4sIAAAAAAAC/0TMMQoCMRCF4X5OMaTSwlzCyka8wmCeu4tkdonphnd3IUHsfmZ4X0TBa3NoWmEFLZES
0cwXaL7utcL7h4zI4wEveiHlsOfbFmhEfswkRbZ67K3r6S/cxmUCd6sgNY1NX8k0QVLOv/oGAAD//1fU
3eyPAAAA
`,
	},

	"/templates/inline.tmpl": {
		name:    "inline.tmpl",
		local:   "templates/inline.tmpl",
		size:    49,
		modtime: 1617338274,
		compressed: `
H4sIAAAAAAAC/6quTklNy8xLVVDKzMvJzEtVqq1VqK4uSc0tyEksSVVQSk7MyVFS0AOLpual1NYCAgAA
//+q60H/MQAAAA==
`,
	},

	"/templates/inputs.tmpl": {
		name:    "inputs.tmpl",
		local:   "templates/inputs.tmpl",
		size:    177,
		modtime: 1617338274,
		compressed: `
H4sIAAAAAAAC/0yNMaoDMQxE+38KsWz58QECOUCaEMgJFCwvLqwESVsJ3T1YpHAlzWN4416pdSbYOn9O
0y3CfW9wuUKZb2/Ab4PyPF9GarqyOw6qEWbFnbhGMA76h1/I3t7KQzrbLeUTCvJByVFwkJFoKlAOLe5J
5/TiWc/fNwAA//94+RPrsQAAAA==
`,
	},

	"/templates/message.tmpl": {
		name:    "message.tmpl",
		local:   "templates/message.tmpl",
		size:    201,
		modtime: 1617338274,
		compressed: `
H4sIAAAAAAAC/zyN4WqDQBCE//sUiyi0oPsAhT5A/xRpS/9f4mgW9GLuTkNY9t2DB/HXDDPDN6o9BvGg
ckaMbkRJrVmhKgP5ayL+XU8JMUWz+sakCt+bqd4lXYh/cIZsCHvCf48F/O+mFWZ8DPnbzTB7y0Tugvj0
5Zd1B6oG50dQJQ1VmOjjk7hzwc1ICLmXgSoxa16/9XZws7wXqi1l+wwAAP//kC65UskAAAA=
`,
	},

	"/templates/results.tmpl": {
		name:    "results.tmpl",
		local:   "templates/results.tmpl",
		size:    168,
		modtime: 1617338274,
		compressed: `
H4sIAAAAAAAC/1yNTQrCQAyFr/Iosyw9gOBS3HsDoRkJlAy8ma5C7i6pRcFVfr4vee6rVDXBROn7NvoU
AXc+7SUoOqPIhssVy+ODI9y1omjEDHexNTf3NrBkc85a82DstH4jG1MW8uQ4hMbv0385A3/uUd8BAAD/
/7BPz2GoAAAA
`,
	},

	"/templates": {
		name:  "templates",
		local: `templates`,
		isDir: true,
	},
}

var _escDirs = map[string][]os.FileInfo{

	"templates": {
		_escData["/templates/call.tmpl"],
		_escData["/templates/function.tmpl"],
		_escData["/templates/header.tmpl"],
		_escData["/templates/inline.tmpl"],
		_escData["/templates/inputs.tmpl"],
		_escData["/templates/message.tmpl"],
		_escData["/templates/results.tmpl"],
	},
}
